class Move:

    def __init__(self, type, physical, power, accuracy, base_pp, tm, bit):
        self.type = type
        self.physical = physical
        self.base_pp = base_pp
        self.power = power
        self.accuracy = accuracy
        self.tm = tm
        self.bit = bit


moves = ["",  # No Move 0
         "Pound",
         "Karate Chop",
         "Double Slap",
         "Comet Punch",
         "Mega Punch",
         "Pay Day",
         "Fire Punch",
         "Ice Punch",
         "Thunder Punch",
         "Scratch",  # 10
         "ViceGrip",
         "Guillotine",
         "Razor Wind",
         "Swords Dance",
         "Cut",
         "Gust",
         "Wing Attack",
         "Whirlwind",
         "Fly",
         "Bind",  # 20
         "Slam",
         "Vine Whip",
         "Stomp",
         "Double Kick",
         "Mega Kick",
         "Jump Kick",
         "Rolling Kick",
         "Sand-Attack",
         "Headbutt",
         "Horn Attack",  # 30
         "Fury Attack",
         "Horn Drill",
         "Tackle",
         "Body Slam",
         "Wrap",
         "Take Down",
         "Thrash",
         "Double-Edge",
         "Tail Whip",
         "Poison Sting",  # 40
         "Twineedle",
         "Pin Missile",
         "Leer",
         "Bite",
         "Growl",  # 45
         "Roar",
         "Sing",
         "Supersonic",
         "SonicBoom",
         "Disable",  # 50
         "Acid",
         "Ember",
         "Flamethrower",
         "Mist",
         "Water Gun",
         "Hydro Pump",
         "Surf",
         "Ice Beam",
         "Blizzard",
         "Psybeam",  # 60
         "BubbleBeam",
         "Aurora Beam",
         "Hyper Beam",
         "Peck",
         "Drill Peck",
         "Submission",
         "Low Kick",
         "Counter",
         "Seismic Toss",
         "Strength",  # 70
         "Absorb",
         "Mega Drain",
         "Leech Seed",
         "Growth",
         "Razor Leaf",
         "SolarBeam",
         "PoisonPowder",
         "Stun Spore",
         "Sleep Powder",
         "Petal Dance",  # 80
         "String Shot",
         "Dragon Rage",
         "Fire Spin",
         "ThunderShock",
         "Thunderbolt",
         "Thunder Wave",
         "Thunder",
         "Rock Throw",
         "Earthquake",
         "Fissure",  # 90
         "Dig",
         "Toxic",
         "Confusion",
         "Psychic",
         "Hypnosis",
         "Meditate",
         "Agility",
         "Quick Attack",
         "Rage",
         "Teleport",  # 100
         "Night Shade",
         "Mimic",
         "Screech",
         "Double Team",
         "Recover",
         "Harden",
         "Minimize",
         "Smokescreen",
         "Confuse Ray",
         "Withdraw",  # 110
         "Defense Curl",
         "Barrier",
         "Light Screen",
         "Haze",
         "Reflect",
         "Focus Energy",
         "Bide",
         "Metronome",
         "Mirror Move",
         "Selfdestruct",  # 120
         "Egg Bomb",
         "Lick",
         "Smog",
         "Sludge",
         "Bone Club",
         "Fire Blast",
         "Waterfall",
         "Clamp",
         "Swift",
         "Skull Bash",  # 130
         "Spike Cannon",
         "Constrict",
         "Amnesia",
         "Kinesis",
         "Softboiled",
         "Hi Jump Kick",
         "Glare",
         "Dream Eater",
         "Poison Gas",
         "Barrage",  # 140
         "Leech Life",
         "Lovely Kiss",
         "Sky Attack",
         "Transform",
         "Bubble",
         "Dizzy Punch",
         "Spore",
         "Flash",
         "Psywave",
         "Splash",  # 150
         "Acid Armor",
         "Crabhammer",
         "Explosion",
         "Fury Swipes",
         "Bonemerang",
         "Rest",
         "Rock Slide",
         "Hyper Fang",
         "Sharpen",
         "Conversion",  # 160
         "Tri Attack",
         "Super Fang",
         "Slash",
         "Substitute",
         "Struggle"]

pound = Move("Normal",
             True,
             35,
             40,
             100,
             False,
             1)
karate_chop = Move("Fighting",
                   True,
                   25,
                   50,
                   100,
                   False,
                   2)
double_slap = Move("Normal",
                   True,
                   10,
                   15,
                   85,
                   False,
                   3)
comet_punch = Move("Normal",
                   True,
                   15,
                   18,
                   85,
                   False,
                   4)
mega_punch = Move("Normal",
                  True,
                  20,
                  80,
                  85,
                  True,
                  5)
pay_day = Move("Normal",
               True,
               20,
               40,
               100,
               True,
               6)
fire_punch = Move("Fire",
                  False,
                  15,
                  75,
                  100,
                  False,
                  7)
ice_punch = Move("",
                 True,
                 15,
                 75,
                 100,
                 False,
                 8)
thunder_punch = Move("",
                     True,
                     15,
                     75,
                     100,
                     False,
                     9)
scratch = Move("Normal",
               True,
               35,
               40,
               100,
               False,
               10)
vicegrip = Move("Normal",
                True,
                30,
                55,
                100,
                False,
                11)
guillotine = Move("Normal",
                  True,
                  5,
                  None,
                  30,
                  False,
                  12)
razor_wind = Move("Normal",
                  True,
                  10,
                  80,
                  100,
                  True,
                  13)
swords_dance = Move("Normal",
                    True,
                    20,
                    None,
                    None,
                    True,
                    14)
cut = Move("Normal",
           True,
           30,
           50,
           95,
           False,
           15)
gust = Move("Flying",
            True,
            35,
            40,
            100,
            False,
            16)
wing_attack = Move("Flying",
                   True,
                   35,
                   60,
                   100,
                   False,
                   17)
whirlwind = Move("Normal",
                 True,
                 20,
                 None,
                 None,
                 True,
                 18)
fly = Move("Flying",
           True,
           15,
           90,
           95,
           False,
           19)
bind = Move("Normal",
            True,
            20,
            15,
            85,
            False,
            20)
slam = Move("Normal",
            True,
            20,
            80,
            75,
            False,
            21)
vine_whip = Move("Grass",
                 False,
                 25,
                 45,
                 100,
                 False,
                 22)
stomp = Move("Normal",
             True,
             20,
             65,
             100,
             False,
             23)
double_kick = Move("Fighting",
                   True,
                   30,
                   30,
                   100,
                   False,
                   24)
mega_kick = Move("Normal",
                 True,
                 5,
                 120,
                 75,
                 True,
                 25)
jump_kick = Move("Fighting",
                 True,
                 10,
                 100,
                 95,
                 False,
                 26)
rolling_kick = Move("Fighting",
                    True,
                    15,
                    60,
                    85,
                    False,
                    27)
sandattack = Move("Ground",
                  True,
                  15,
                  None,
                  100,
                  False,
                  28)
headbutt = Move("Normal",
                True,
                15,
                70,
                100,
                False,
                29)
horn_attack = Move("Normal",
                   True,
                   25,
                   65,
                   100,
                   False,
                   30)
fury_attack = Move("Normal",
                   True,
                   20,
                   15,
                   85,
                   False,
                   31)
horn_drill = Move("Normal",
                  True,
                  5,
                  None,
                  30,
                  True,
                  32)
tackle = Move("Normal",
              True,
              35,
              40,
              100,
              False,
              33)
body_slam = Move("Normal",
                 True,
                 15,
                 85,
                 100,
                 True,
                 34)
wrap = Move("Normal",
            True,
            20,
            15,
            90,
            False,
            35)
take_down = Move("Normal",
                 True,
                 20,
                 90,
                 85,
                 True,
                 36)
thrash = Move("Normal",
              True,
              10,
              120,
              100,
              False,
              37)
doubleedge = Move("Normal",
                  True,
                  15,
                  120,
                  100,
                  False,
                  38)
tail_whip = Move("Normal",
                 True,
                 30,
                 None,
                 100,
                 False,
                 39)
poison_sting = Move("Poison",
                    True,
                    35,
                    15,
                    100,
                    False,
                    40)
twineedle = Move("Bug",
                 True,
                 20,
                 25,
                 100,
                 False,
                 41)
pin_missile = Move("Bug",
                   True,
                   20,
                   25,
                   95,
                   False,
                   42)
leer = Move("Normal",
            True,
            30,
            None,
            100,
            False,
            43)
bite = Move("",
            True,
            25,
            60,
            100,
            False,
            44)
growl = Move("Normal",
             True,
             40,
             None,
             100,
             False,
             45)
roar = Move("Normal",
            True,
            20,
            None,
            None,
            False,
            46)
sing = Move("Normal",
            True,
            15,
            None,
            55,
            False,
            47)
supersonic = Move("Normal",
                  True,
                  20,
                  None,
                  55,
                  False,
                  48)
sonicboom = Move("Normal",
                 True,
                 20,
                 None,
                 90,
                 False,
                 49)
disable = Move("Normal",
               True,
               20,
               None,
               100,
               False,
               50)
acid = Move("Poison",
            True,
            30,
            40,
            100,
            False,
            51)
ember = Move("Fire",
             False,
             25,
             40,
             100,
             False,
             52)
flamethrower = Move("Fire",
                    False,
                    15,
                    90,
                    100,
                    False,
                    53)
mist = Move("Ice",
            True,
            30,
            None,
            None,
            False,
            54)
water_gun = Move("Water",
                 False,
                 25,
                 40,
                 100,
                 True,
                 55)
hydro_pump = Move("Water",
                  False,
                  5,
                  110,
                  80,
                  False,
                  56)
surf = Move("Water",
            False,
            15,
            90,
            100,
            False,
            57)
ice_beam = Move("Ice",
                True,
                10,
                90,
                100,
                True,
                58)
blizzard = Move("Ice",
                True,
                5,
                110,
                70,
                True,
                59)
psybeam = Move("Psychic",
               False,
               20,
               65,
               100,
               False,
               60)
bubblebeam = Move("Water",
                  False,
                  20,
                  65,
                  100,
                  False,
                  61)
aurora_beam = Move("",
                   True,
                   20,
                   65,
                   100,
                   False,
                   62)
hyper_beam = Move("Normal",
                  True,
                  5,
                  150,
                  90,
                  True,
                  63)
peck = Move("Flying",
            True,
            35,
            35,
            100,
            False,
            64)
drill_peck = Move("Flying",
                  True,
                  20,
                  80,
                  100,
                  False,
                  65)
submission = Move("Fighting",
                  True,
                  20,
                  80,
                  80,
                  True,
                  66)
low_kick = Move("Fighting",
                True,
                20,
                None,
                100,
                False,
                67)
counter = Move("Fighting",
               True,
               20,
               None,
               100,
               True,
               68)
seismic_toss = Move("Fighting",
                    True,
                    20,
                    None,
                    100,
                    True,
                    69)
strength = Move("Normal",
                True,
                15,
                80,
                100,
                False,
                70)
absorb = Move("Grass",
              False,
              25,
              20,
              100,
              False,
              71)
mega_drain = Move("Grass",
                  False,
                  15,
                  40,
                  100,
                  True,
                  72)
leech_seed = Move("Grass",
                  False,
                  10,
                  None,
                  90,
                  False,
                  73)
growth = Move("Normal",
              True,
              20,
              None,
              None,
              False,
              74)
razor_leaf = Move("Grass",
                  False,
                  25,
                  55,
                  95,
                  False,
                  75)
solarbeam = Move("Grass",
                 False,
                 10,
                 120,
                 100,
                 False,
                 76)
poisonpowder = Move("Poison",
                    True,
                    35,
                    None,
                    75,
                    False,
                    77)
stun_spore = Move("Grass",
                  False,
                  30,
                  None,
                  75,
                  False,
                  78)
sleep_powder = Move("Grass",
                    False,
                    15,
                    None,
                    75,
                    False,
                    79)
petal_dance = Move("Grass",
                   False,
                   10,
                   120,
                   100,
                   False,
                   80)
string_shot = Move("Bug",
                   True,
                   40,
                   None,
                   95,
                   False,
                   81)
dragon_rage = Move("Dragon",
                   True,
                   10,
                   None,
                   100,
                   True,
                   82)
fire_spin = Move("Fire",
                 False,
                 15,
                 35,
                 85,
                 False,
                 83)
thundershock = Move("Electric",
                    True,
                    30,
                    40,
                    100,
                    False,
                    84)
thunderbolt = Move("Electric",
                   True,
                   15,
                   90,
                   100,
                   True,
                   85)
thunder_wave = Move("Electric",
                    True,
                    20,
                    None,
                    90,
                    True,
                    86)
thunder = Move("Electric",
               True,
               10,
               110,
               70,
               True,
               87)
rock_throw = Move("Rock",
                  True,
                  15,
                  50,
                  90,
                  False,
                  88)
earthquake = Move("Ground",
                  True,
                  10,
                  100,
                  100,
                  True,
                  89)
fissure = Move("Ground",
               True,
               5,
               None,
               30,
               True,
               90)
dig = Move("Ground",
           True,
           10,
           80,
           100,
           True,
           91)
toxic = Move("Poison",
             True,
             10,
             None,
             90,
             True,
             92)
confusion = Move("Psychic",
                 False,
                 25,
                 50,
                 100,
                 False,
                 93)
psychic = Move("Psychic",
               False,
               10,
               90,
               100,
               True,
               94)
hypnosis = Move("Psychic",
                False,
                20,
                None,
                60,
                False,
                95)
meditate = Move("Psychic",
                False,
                40,
                None,
                None,
                False,
                96)
agility = Move("Psychic",
               False,
               30,
               None,
               None,
               False,
               97)
quick_attack = Move("Normal",
                    True,
                    30,
                    40,
                    100,
                    False,
                    98)
rage = Move("Normal",
            True,
            20,
            20,
            100,
            True,
            99)
teleport = Move("Psychic",
                False,
                20,
                None,
                None,
                True,
                100)
night_shade = Move("Ghost",
                   True,
                   15,
                   None,
                   100,
                   False,
                   101)
mimic = Move("Normal",
             True,
             10,
             None,
             None,
             True,
             102)
screech = Move("Normal",
               True,
               40,
               None,
               85,
               False,
               103)
double_team = Move("Normal",
                   True,
                   15,
                   None,
                   None,
                   True,
                   104)
recover = Move("Normal",
               True,
               5,
               None,
               None,
               False,
               105)
harden = Move("Normal",
              True,
              30,
              None,
              None,
              False,
              106)
minimize = Move("Normal",
                True,
                10,
                None,
                None,
                False,
                107)
smokescreen = Move("Normal",
                   True,
                   20,
                   None,
                   100,
                   False,
                   108)
confuse_ray = Move("Ghost",
                   True,
                   10,
                   None,
                   100,
                   False,
                   109)
withdraw = Move("Water",
                False,
                40,
                None,
                None,
                False,
                110)
defense_curl = Move("Normal",
                    True,
                    40,
                    None,
                    None,
                    False,
                    111)
barrier = Move("Psychic",
               False,
               20,
               None,
               None,
               False,
               112)
light_screen = Move("Psychic",
                    False,
                    30,
                    None,
                    None,
                    False,
                    113)
haze = Move("",
            True,
            30,
            None,
            None,
            False,
            114)
reflect = Move("Psychic",
               False,
               20,
               None,
               None,
               True,
               115)
focus_energy = Move("Normal",
                    True,
                    30,
                    None,
                    None,
                    False,
                    116)
bide = Move("Normal",
            True,
            10,
            None,
            None,
            True,
            117)
metronome = Move("Normal",
                 True,
                 10,
                 None,
                 None,
                 True,
                 118)
mirror_move = Move("Flying",
                   True,
                   20,
                   None,
                   None,
                   False,
                   119)
selfdestruct = Move("Normal",
                    True,
                    5,
                    200,
                    100,
                    False,
                    120)
egg_bomb = Move("Normal",
                True,
                10,
                100,
                75,
                True,
                121)
lick = Move("Ghost",
            True,
            30,
            30,
            100,
            False,
            122)
smog = Move("Poison",
            True,
            20,
            30,
            70,
            False,
            123)
sludge = Move("Poison",
              True,
              20,
              65,
              100,
              False,
              124)
bone_club = Move("Ground",
                 True,
                 20,
                 65,
                 85,
                 False,
                 125)
fire_blast = Move("Fire",
                  False,
                  5,
                  110,
                  85,
                  True,
                  126)
waterfall = Move("Water",
                 False,
                 15,
                 80,
                 100,
                 False,
                 127)
clamp = Move("Water",
             False,
             15,
             35,
             85,
             False,
             128)
swift = Move("Normal",
             True,
             20,
             60,
             None,
             True,
             129)
skull_bash = Move("Normal",
                  True,
                  10,
                  130,
                  100,
                  True,
                  130)
spike_cannon = Move("Normal",
                    True,
                    15,
                    20,
                    100,
                    False,
                    131)
constrict = Move("Normal",
                 True,
                 35,
                 10,
                 100,
                 False,
                 132)
amnesia = Move("Psychic",
               False,
               20,
               None,
               None,
               False,
               133)
kinesis = Move("Psychic",
               False,
               15,
               None,
               80,
               False,
               134)
softboiled = Move("Normal",
                  True,
                  5,
                  None,
                  None,
                  False,
                  135)
high_jump_kick = Move("Fighting",
                      True,
                      10,
                      130,
                      90,
                      False,
                      136)
glare = Move("Normal",
             True,
             30,
             None,
             100,
             False,
             137)
dream_eater = Move("Psychic",
                   False,
                   15,
                   100,
                   100,
                   True,
                   138)
poison_gas = Move("Poison",
                  True,
                  40,
                  None,
                  90,
                  False,
                  139)
barrage = Move("Normal",
               True,
               20,
               15,
               85,
               False,
               140)
leech_life = Move("Bug",
                  True,
                  10,
                  80,
                  100,
                  False,
                  141)
lovely_kiss = Move("Normal",
                   True,
                   10,
                   None,
                   75,
                   False,
                   142)
sky_attack = Move("Flying",
                  True,
                  5,
                  140,
                  90,
                  True,
                  143)
transform = Move("Normal",
                 True,
                 10,
                 None,
                 None,
                 False,
                 144)
bubble = Move("Water",
              False,
              30,
              40,
              100,
              False,
              145)
dizzy_punch = Move("Normal",
                   True,
                   10,
                   70,
                   100,
                   False,
                   146)
spore = Move("Grass",
             False,
             15,
             None,
             100,
             False,
             147)
flash = Move("Normal",
             True,
             20,
             None,
             100,
             False,
             148)
psywave = Move("Psychic",
               False,
               15,
               None,
               100,
               True,
               149)
splash = Move("Normal",
              True,
              40,
              None,
              None,
              False,
              150)
acid_armor = Move("Poison",
                  True,
                  20,
                  None,
                  None,
                  False,
                  151)
crabhammer = Move("Water",
                  False,
                  10,
                  100,
                  90,
                  False,
                  152)
explosion = Move("Normal",
                 True,
                 5,
                 250,
                 100,
                 True,
                 153)
fury_swipes = Move("Normal",
                   True,
                   15,
                   18,
                   80,
                   False,
                   154)
bonemerang = Move("Ground",
                  True,
                  10,
                  50,
                  90,
                  False,
                  155)
rest = Move("Psychic",
            False,
            5,
            None,
            None,
            True,
            156)
rock_slide = Move("Rock",
                  True,
                  10,
                  75,
                  90,
                  True,
                  157)
hyper_fang = Move("Normal",
                  True,
                  15,
                  80,
                  90,
                  False,
                  158)
sharpen = Move("Normal",
               True,
               30,
               None,
               None,
               False,
               159)
conversion = Move("Normal",
                  True,
                  30,
                  None,
                  None,
                  False,
                  160)
tri_attack = Move("Normal",
                  True,
                  10,
                  80,
                  100,
                  True,
                  161)
super_fang = Move("Normal",
                  True,
                  10,
                  None,
                  90,
                  False,
                  162)
slash = Move("Normal",
             True,
             20,
             70,
             100,
             False,
             163)
substitute = Move("Normal",
                  True,
                  10,
                  None,
                  None,
                  True,
                  164)
struggle = Move("Normal",
                True,
                1,
                50,
                None,
                False,
                165)

tms = ["Mega Punch",
       "Razor Wind",
       "Swords Dance",
       "Whirlwind",
       "Mega Kick",
       "Toxic",
       "Horn Drill",
       "Body Slam",
       "Take Down",
       "Double-Edge",
       "BubbleBeam",
       "Water Gun",
       "Ice Beam",
       "Blizzard",
       "Hyper Beam",
       "Pay Day",
       "Submission",
       "Counter",
       "Seismic Toss",
       "Rage",
       "Mega Drain",
       "SolarBeam",
       "Dragon Rage",
       "Thunderbolt",
       "Thunder",
       "Earthquake",
       "Fissure",
       "Dig",
       "Psychic",
       "Teleport",
       "Mimic",
       "Double Team",
       "Reflect",
       "Bide",
       "Metronome",
       "Selfdestruct",
       "Egg Bomb",
       "Fire Blast",
       "Swift",
       "Skull Bash",
       "Softboiled",
       "Dream Eater",
       "Sky Attack",
       "Rest",
       "Thunder Wave",
       "Psywave",
       "Explosion",
       "Rock Slide",
       "Tri Attack",
       "Substitute"]
hms = ["Cut",
       "Fly",
       "Surf",
       "Strength",
       "Flash"]
